site_name: Isaac's Docs
repo_name: isaacmaruyama.github.io
repo_url: https://isaacmaruyama.github.io/

theme:
  name: material
  favicon: images/flask.png
  icon:
    logo: material/flask
  font:
    text: Roboto Slab
  palette:
    primary: deep orange
    accent: deep purple
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - footnotes

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js